module.exports = {
  listenAddr: {
    port: 8080,
    hostname: '0.0.0.0',
  },
  // axiosOptions are the options of the proxy request
  axiosOptions: {
    timeout: 60000, // 60s
  },
  rpcEndpoint: 'http://localhost:26657/',
  redisConfig: {
    url: 'redis://localhost:6379',
  },
  cache: {
    method: {
      // negative number means blacklist
      broadcast_tx: -1,
      broadcast_tx_sync: -1,
      broadcast_tx_async: -1,
      broadcast_tx_commit: -1,
      check_tx: -1,
      subscribe: -1,
      unsubscribe: -1,
      unsubscribe_all: -1,
      dial_seeds: -1,
      dial_peers: -1,
      unsafe_flush_mempool: -1,
      remove_tx: -1,

      // RPC methods
      block_by_hash: 3600,
      consensus_params: 3600,
      genesis: 3600,
      genesis_chunked: 3600,
      tx: 3600,
      validators: 3600,

      block: (jsonRpcRequest) => {
        const height = jsonRpcRequest.params.height;
        if (!height || height === '0') {
          // don't match with this matcher, fallback to the default
          return 0;
        }
        return 3600;
      },
    },
    abciQuery: {
      '/cosmos.auth.v1beta1.Query/Params': 3600,
      '/cosmos.authz.v1beta1.Query/GranteeGrants': 60,
      '/cosmos.authz.v1beta1.Query/GranterGrants': 60,
      '/cosmos.authz.v1beta1.Query/Grants': 60,
      '/cosmos.bank.v1beta1.Query/DenomMetadata': 3600,
      '/cosmos.bank.v1beta1.Query/DenomsMetadata': 3600,
      '/cosmos.bank.v1beta1.Query/Params': 3600,
      '/cosmos.base.tendermint.v1beta1.Service/GetBlockByHeight': 3600,
      '/cosmos.base.tendermint.v1beta1.Service/GetValidatorSetByHeight': 3600,
      '/cosmos.distribution.v1beta1.Query/DelegatorValidators': 60,
      '/cosmos.distribution.v1beta1.Query/DelegatorWithdrawAddress': 3600,
      '/cosmos.distribution.v1beta1.Query/Params': 3600,
      '/cosmos.distribution.v1beta1.Query/ValidatorSlashes': 60,
      '/cosmos.evidence.v1beta1.Query/AllEvidence': 60,
      '/cosmos.evidence.v1beta1.Query/Evidence': 60,
      '/cosmos.feegrant.v1beta1.Query/Allowance': 60,
      '/cosmos.feegrant.v1beta1.Query/Allowances': 60,
      '/cosmos.feegrant.v1beta1.Query/AllowancesByGranter': 60,
      '/cosmos.gov.v1beta1.Query/Deposit': 60,
      '/cosmos.gov.v1beta1.Query/Deposits': 60,
      '/cosmos.gov.v1beta1.Query/Params': 3600,
      '/cosmos.gov.v1beta1.Query/Proposal': 60,
      '/cosmos.gov.v1beta1.Query/Proposals': 60,
      '/cosmos.gov.v1beta1.Query/TallyResult': 3600,
      '/cosmos.gov.v1beta1.Query/Vote': 60,
      '/cosmos.gov.v1beta1.Query/Votes': 60,
      '/cosmos.mint.v1beta1.Query/AnnualProvisions': 60,
      '/cosmos.mint.v1beta1.Query/Inflation': 60,
      '/cosmos.mint.v1beta1.Query/Params': 3600,
      '/cosmos.params.v1beta1.Query/Params': 3600,
      '/cosmos.slashing.v1beta1.Query/Params': 3600,
      '/cosmos.slashing.v1beta1.Query/SigningInfo': 60,
      '/cosmos.slashing.v1beta1.Query/SigningInfos': 60,
      '/cosmos.staking.v1beta1.Query/Delegation': 60,
      '/cosmos.staking.v1beta1.Query/DelegatorDelegations': 60,
      '/cosmos.staking.v1beta1.Query/DelegatorUnbondingDelegations': 60,
      '/cosmos.staking.v1beta1.Query/DelegatorValidator': 60,
      '/cosmos.staking.v1beta1.Query/DelegatorValidators': 60,
      '/cosmos.staking.v1beta1.Query/HistoricalInfo': 60,
      '/cosmos.staking.v1beta1.Query/Params': 3600,
      '/cosmos.staking.v1beta1.Query/Redelegations': 60,
      '/cosmos.staking.v1beta1.Query/UnbondingDelegation': 60,
      '/cosmos.staking.v1beta1.Query/Validator': 60,
      '/cosmos.staking.v1beta1.Query/Validators': 60,
      '/cosmos.upgrade.v1beta1.Query/AppliedPlan': 600,
      '/cosmos.upgrade.v1beta1.Query/CurrentPlan': 600,
      '/cosmos.upgrade.v1beta1.Query/ModuleVersions': 600,
      '/cosmos.upgrade.v1beta1.Query/UpgradedConsensusState': 600,
      '/likechain.iscn.Query/GetCid': 3600,
      '/likechain.iscn.Query/GetCidSize': 3600,
      '/likechain.iscn.Query/Params': 3600,
      '/likechain.iscn.Query/RecordsByFingerprint': 60,
      // TODO: parse ISCN ID and cache longer if requested version !== 0
      '/likechain.iscn.Query/RecordsById': 60,
      '/likechain.iscn.Query/RecordsByOwner': 60,
      '/cosmos.nft.v1beta1.Query/Balance': 60,
      '/cosmos.nft.v1beta1.Query/Class': 60,
      '/cosmos.nft.v1beta1.Query/Classes': 60,
      '/cosmos.nft.v1beta1.Query/NFT': 60,
      '/cosmos.nft.v1beta1.Query/NFTs': 60,
      '/cosmos.nft.v1beta1.Query/Owner': 60,
      '/cosmos.nft.v1beta1.Query/Supply': 60,
      '/likechain.likenft.Query/AccountByClass': 60,
      '/likechain.likenft.Query/ClassesByAccount': 60,
      '/likechain.likenft.Query/ClassesByAccountIndex': 60,
      '/likechain.likenft.Query/ClassesByISCN': 60,
      '/likechain.likenft.Query/ClassesByISCNIndex': 60,
      '/likechain.likenft.Query/ISCNByClass': 60,
      '/likechain.likenft.Query/Listing': 60,
      '/likechain.likenft.Query/ListingIndex': 60,
      '/likechain.likenft.Query/ListingsByClass': 60,
      '/likechain.likenft.Query/ListingsByNFT': 60,
      '/likechain.likenft.Query/MintableNFT': 60,
      '/likechain.likenft.Query/MintableNFTIndex': 60,
      '/likechain.likenft.Query/MintableNFTs': 60,
      '/likechain.likenft.Query/Offer': 60,
      '/likechain.likenft.Query/OfferIndex': 60,
      '/likechain.likenft.Query/OffersByClass': 60,
      '/likechain.likenft.Query/OffersByNFT': 60,
      '/likechain.likenft.Query/Params': 60,
      '/likechain.likenft.Query/RoyaltyConfig': 60,
      '/likechain.likenft.Query/RoyaltyConfigIndex': 60,
    },
    default: 10,
  },
  pubsub: {
    GCLOUD_PUBSUB_ENABLE: true,
    GCLOUD_PUBSUB_MAX_MESSAGES: 10,
    GCLOUD_PUBSUB_MAX_WAIT: 1000,
    APP_SERVER: 'json-rpc-cache',
  },
};
