version: "3.6"
services:
  redis:
    image: redis:6
    restart: always
  rpc-cache:
    build: .
    ports:
      - 8080:8080
    volumes:
      - "./jsonrpc-config.json:/jsonrpc-config.json"
    command: [
      "/bin/main",
      "--rpc", "http://somewhere:26657/",
      "--redis", "redis:6379",
      "--listen", "0.0.0.0:8080",
      "--jsonrpc-config-file", "/jsonrpc-config.json",
      "--log-level", "info",
      "--log-outputs", "stderr",
    ]
    restart: always
