version: "3.6"
services:
  redis:
    image: redis:6
    restart: always
  rpc-cache:
    build: .
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
    restart: always
    command: ['node', 'index.js']
