version: "3.6"
services:
  redis:
    image: redis:6
    restart: always
  rpc-cache:
    build: .
    ports:
      - 8080:8080
    command: [
      "/bin/main",
      "--rpc", "http://somewhere:26657/",
      "--redis", "redis:6379",
      "--listen", "0.0.0.0:8080"
    ]
    restart: always
